# environment.yml

name: dsit_chemflow
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - pytorch=2.7.0
  - torchtext=0.18.0
  - pytorch-cuda=11.8 -c pytorch -c nvidia
  - accelerate=0.25.0
  - lightning=2.1.4        
  - botorch=0.14.0         
  - gpytorch=1.14          

  - rdkit=2023.9.3         
  - openbabel=3.1.1.1
  - selfies=2.1.2
  - pubchempy=1.0.4
  - numpy=2.3.1
  - pandas=2.3.0
  - pandarallel=1.6.5
  - scipy=1.16.0
  - scikit-learn=1.0.2
  - matplotlib=3.10.3
  - pillow=11.2.1
  - tqdm=4.67.1

  - hydra-core=1.3.2
  - omegaconf=2.3.0
  - absl-py=2.2.0
  - attrs=25.3.0
  - certifi=2025.4.26
  - regex=2024.11.6
  - setuptools=75.8.2

  - pip:
    - cd2root==0.1.6
    - dict_hash==1.3.6
    - fcd-torch==1.0.7
    - moses-lib==0.10.0  
    - pytdc==0.4.1
    - python-hostlist==2.2.1
    - torchdiffeq==0.2.5
    - typed-argument-parser==1.10.1